<a href="https://colab.research.google.com/github/arunprasath2007/FrameworkILoveAndToExperiment/blob/master/Neural_Networks_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Single Neuron (single input, weight, bias)


In [4]:
input = 2.0

weight = 3.0
bias = 1.0

output = input * weight + bias
output

7.0

Single Neuron (multiple input and weights, bias)

In [5]:
inputs = [1.0, 2.0, 3.5]


weights = [1.5, 2.4, 5.4]
bias = 2.0

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
output

27.200000000000003

Two neuron, 3 inputs, 2 weight parameters, 2 bias

In [8]:
inputs = [1.0, 2.0, 3.5]

weight1 = [1.5, 2.4, 5.4]
weight2 = [3.2, 2.3, 1.6]

bias1 = 2.0
bias2 = 2.1

output1 = inputs[0]*weight1[0] + inputs[1]*weight1[1] + inputs[2]*weight1[2] + bias1
output2 = inputs[0]*weight2[0] + inputs[1]*weight2[1] + inputs[2]*weight2[2] + bias2

print(output1)
print(output2)

27.200000000000003
15.5


Plain loop

In [19]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

layered_outputs = []

for neuron_weight, neuron_bias in zip(weights, biases):
  neuron_output = 0

  for neuron_input, weight in zip(inputs, neuron_weight):
    neuron_output += neuron_input * weight
  output = neuron_output + neuron_bias

  layered_outputs.append(output)

layered_outputs



[4.8, 1.21, 2.385]

Using Numpy

In [23]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]

layered_outputs = np.dot(weights, inputs) + biases
layered_outputs_T = np.dot(inputs, np.array(weights).T) + biases

print(layered_outputs)
print(layered_outputs_T)

[4.8   1.21  2.385]
[4.8   1.21  2.385]


Dot product of two vectors


In [4]:
import numpy as np

a = [1, 2, 3]
b = [2, 3, 4]

a = np.array([a])
b = np.array([b]).T

c =np.dot(a, b) 
c

array([[20]])

Inputs as batches (This is where Matrix product comes into picture)

In [6]:
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]

output = np.dot(inputs, np.array(weights).T) + biases
output



array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

2 Layer neural network

In [14]:
inputs = [[1, 2, 3, 2.5], [2., 5., -1., 2], [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

layered1_output = np.dot(inputs, np.array(weights).T) + biases
layered2_output = np.dot(layered1_output, np.array(weights2).T) + biases2
print(layered2_output)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
