<a href="https://colab.research.google.com/github/arunprasath2007/FrameworkILoveAndToExperiment/blob/master/Neural_network_DenseLayers_With_Activation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

n_inputs = 4
n_neurons = 3

f = np.random.randn(n_inputs, n_neurons) * 0.01
print(f)

b = np.zeros((1, n_neurons))
print(b)

[[-0.00365605  0.01859097  0.00385326]
 [ 0.00558719 -0.01607076  0.00120972]
 [-0.00216816 -0.00134624 -0.00961468]
 [-0.01091849 -0.01075953  0.00672779]]
[[0. 0. 0.]]


In [2]:
pip install nnfs

In [3]:
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()


In [7]:

class Layers_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))
  
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases


In [8]:
class Activation_ReLU:
  def forward(self, inputs):
    self.outputs = np.maximum(0, inputs)

In [11]:
class Activation_Softmax:
  def forward(self, inputs):
    exponents = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))

    probabilities = exponents / np.sum(exponents, axis=1, keepdims=True)

    self.outputs = probabilities

In [13]:
X, y = spiral_data(samples=100, classes=3)

dense = Layers_Dense(2, 3)

dense.forward(X)

activation = Activation_ReLU()

activation.forward(dense.output)

print(activation.outputs[:5])

softMax = Activation_Softmax()

softMax.forward(activation.outputs)

print(softMax.outputs[:1])

[[0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 1.7795961e-04 0.0000000e+00]
 [3.0106357e-05 3.6696982e-04 0.0000000e+00]
 [0.0000000e+00 1.9415646e-04 0.0000000e+00]
 [0.0000000e+00 1.6941362e-04 1.2681631e-05]]
[[0.33333334 0.33333334 0.33333334]]


In [39]:
X, y = spiral_data(samples=100, classes=3)

dense1 = Layers_Dense(2, 3)

activation1 = Activation_ReLU()

dense2 = Layers_Dense(3, 3)

activation2 = Activation_Softmax()

dense1.forward(X)

activation1.forward(dense1.output)

dense2.forward(activation1.outputs)

activation2.forward(dense2.output)

print(activation2.outputs[:5])



[[0.33333334 0.33333334 0.33333334]
 [0.33333308 0.3333336  0.3333333 ]
 [0.33333284 0.33333385 0.3333333 ]
 [0.3333326  0.3333341  0.3333333 ]
 [0.33333233 0.3333344  0.3333333 ]]
