<a href="https://colab.research.google.com/github/arunprasath2007/FrameworkILoveAndToExperiment/blob/master/Neural_network_DenseLayers_withSoftmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

n_inputs = 4
n_neurons = 3

f = np.random.randn(n_inputs, n_neurons) * 0.01
print(f)

b = np.zeros((1, n_neurons))
print(b)

[[ 0.00189766  0.00743825 -0.00698525]
 [-0.01220351  0.00242107  0.00136837]
 [ 0.00871411 -0.00993321 -0.00173574]
 [ 0.00801876  0.00333919  0.00458774]]
[[0. 0. 0.]]


In [7]:
pip install nnfs

In [8]:
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()


In [9]:

class Layers_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))
  
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases


In [10]:
class Activation_ReLU:
  def forward(self, inputs):
    self.outputs = np.maximum(0, inputs)

In [8]:
class Activation_Softmax:
  def forward(self, inputs):
    exponents = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))

    probabilities = exponents / np.sum(exponents, axis=1, keepdims=True)

    self.outputs = probabilities

In [12]:
class Loss:
  def calculate(self, y_pred, y_true):
    loss_output = self.forward(y_pred, y_true)

    loss_mean = np.mean(loss_output)

    return loss_mean

In [20]:
class Loss_CategoricalCrossEntropyLoss(Loss):
  def forward(self, y_pred, y_true):
    y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)

    crossEntropyLoss = []

    if len(y_true.shape) == 1:
      crossEntropyLoss = y_pred_clipped[range(len(y_pred)), y_true]

    elif len(y_true.shape) == 2:
      crossEntropyLoss = np.sum(y_pred_clipped * y_true, axis=1)

    log_loss = -np.log(crossEntropyLoss)

    return log_loss  


In [13]:
X, y = spiral_data(samples=100, classes=3)

dense = Layers_Dense(2, 3)

dense.forward(X)

activation = Activation_ReLU()

activation.forward(dense.output)

print(activation.outputs[:5])

softMax = Activation_Softmax()

softMax.forward(activation.outputs)

print(softMax.outputs[:1])

[[0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 1.7795961e-04 0.0000000e+00]
 [3.0106357e-05 3.6696982e-04 0.0000000e+00]
 [0.0000000e+00 1.9415646e-04 0.0000000e+00]
 [0.0000000e+00 1.6941362e-04 1.2681631e-05]]
[[0.33333334 0.33333334 0.33333334]]


In [27]:
X, y = spiral_data(samples=100, classes=3)

print(len(y.shape))


dense1 = Layers_Dense(2, 3)

activation1 = Activation_ReLU()

dense2 = Layers_Dense(3, 3)

activation2 = Activation_Softmax()

loss = Loss_CategoricalCrossEntropyLoss()

dense1.forward(X)

activation1.forward(dense1.output)

dense2.forward(activation1.outputs)

activation2.forward(dense2.output)

catLoss = loss.calculate(activation2.outputs, y)

print(catLoss)



1


'\ndense1 = Layers_Dense(2, 3)\n\nactivation1 = Activation_ReLU()\n\ndense2 = Layers_Dense(3, 3)\n\nactivation2 = Activation_Softmax()\n\nloss = Loss_CategoricalCrossEntropyLoss()\n\ndense1.forward(X)\n\nactivation1.forward(dense1.output)\n\ndense2.forward(activation1.outputs)\n\nactivation2.forward(dense2.output)\n\ncatLoss = loss.calculate(activation2.outputs, y)\n\nprint(catLoss)\n\n'

In [23]:
softmax_outputs = np.array([[0.7, 0.1, 0.2],
                            [0.1, 0.5, 0.4],
                            [0.02, 0.9, 0.08]])
class_targets = np.array([[1, 0, 0],
                          [0, 1, 0],
                          [0, 1, 0]])

loss = Loss_CategoricalCrossEntropyLoss()

catLoss = loss.calculate(softmax_outputs, class_targets)

print(catLoss)


0.38506088005216804


In [12]:
import numpy as np

hidden_layer_output = np.array([[1, -2, 2]])

relu_Output = np.maximum(0, hidden_layer_output)

print(relu_Output)

softMax = Activation_Softmax()

softMax.forward(relu_Output)

print(softMax.outputs)


[[1 0 2]]
[[0.24472847 0.09003057 0.66524096]]
